name: CI

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

  tests:
    name: Unit Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci
